"""feature: se agrega columna de color a horarios

Revision ID: 2317cf523973
Revises: 8aea5ee4bacf
Create Date: 2022-06-14 00:54:05.432066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2317cf523973'
down_revision = '8aea5ee4bacf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
