"""feature: se agrega thumb a video

Revision ID: 8aea5ee4bacf
Revises: f50fce913dc9
Create Date: 2022-06-14 00:51:29.224803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aea5ee4bacf'
down_revision = 'f50fce913dc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumb_file', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('thumb_file')

    # ### end Alembic commands ###
