"""fix: correccion de columna

Revision ID: f50fce913dc9
Revises: 7d05ab9ac7ea
Create Date: 2022-06-14 00:49:41.582413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f50fce913dc9'
down_revision = '7d05ab9ac7ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end', sa.Time(), nullable=False))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TIME(), nullable=False))
        batch_op.drop_column('end')

    # ### end Alembic commands ###
